### ISSUE TITLE
Training parameter problem

### ISSUE THREAD

**Issue by leslieAIbin** [sj-li/MS-TCN2#1]
How many epochs did you run in each dataset? I see in the code that the number of epoch you set is 100. Is this inconsistent with the original ms-tcn?

**Comment by txyxju1997** [comment]
super(MS_TCB, self).__init__()？I think it is super(MS_TCN, self).__init__()?

**Comment by sj-li** [comment]
> super(MS_TCB, self).**init**()？I think it is super(MS_TCN, self).**init**()?

Yes, this is an error and I already fixed it, thanks :)

**Comment by sj-li** [comment]
> How many epochs did you run in each dataset? I see in the code that the number of epoch you set is 100. Is this inconsistent with the original ms-tcn?

Sorry for the late reply.
Yes, I train for 100 epochs and select the epoch number that can achieve the best average result for the 5 splits to report the number.
