### ISSUE TITLE
Performance variance

### ISSUE THREAD

**Issue by jasper0401** [sj-li/MS-TCN2#2]
Hi Li, 

Many thanks for sharing the code and I really like this interesting work. I ran the code on the data your shared, but the performance seems slightly different from the reported in the table. For example, this is the average result for the 5 splits I obtained on 50salads, "Acc:82.03, Edit:72.14, F1@10: 79.51, F1@25: 77.59, F1@50: 69.45". I was wondering what I missed in the reproduction. 

Best regards
ja

**Comment by sj-li** [comment]
Hi:

Thanks for your interests and sorry about late reply.
This may because the training epochs.
I train for 100 epochs and select the epoch number that can achieve the best average result for the 5 splits to report the number.
