### ISSUE TITLE
cannot reproduce paper results with default configuration

### ISSUE THREAD

**Issue by JoursBleu** [sj-li/MS-TCN2#8]
We are using docker image “nvcr.io/nvidia/pytorch:22.03-py3” from NVIDIA
`git clone https://github.com/sj-li/MS-TCN2.git`
`cd MS-TCN2`
`ln -s $data_path dat`
`# dataset in breakfast, 50salads, gtea`
`# split in  (1-5) for 50salads and (1-4) for the other datasets`
`python3 main.py --action=train --dataset=$dataset --split=$split --num_epochs=100 --num_layers_PG=11 --num_layers_R=10 --num_R=3`

The results in paper which is in TABLE 16:
![image](https://user-images.githubusercontent.com/22388449/166231338-b274c672-f74f-4c35-b5a0-bf629d7e6cf8.png)

And all the results mismatch with paper somehow:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/letianka/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/letianka/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/letianka/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>

  | F1 0.10 | F1 0.25 | F1 0.50 | Edit | Acc
-- | -- | -- | -- | -- | --
50salads split 1 | 73.4 | 70.1 | 60.2 | 64.2 | 76.7
50salads split 2 | 72.2 | 69.2 | 59.8 | 64.1 | 81.7
50salads split 3 | 71.5 | 68.4 | 62.3 | 66.3 | 75.2
50salads split 4 | 79.3 | 77.0 | 69.1 | 71.6 | 83.3
50salads split 5 | 80.2 | 77.8 | 72.6 | 71.5 | 86.7
gtea split 1 | 80.1 | 77.4 | 64.6 | 71.5 | 74.4
gtea split 2 | 83.7 | 81.0 | 70.1 | 76.6 | 78.3
gtea split 3 | 90.6 | 89.1 | 79.2 | 88.2 | 79.2
gtea split 4 | 87.9 | 85.6 | 70.5 | 83.1 | 74.9

</body>

</html>

Are these mismatch reasonable, or did I miss any configuration?

**Comment by rickywrq** [comment]
@JoursBleu Have you figured out what is the reason for that?
